object VersionsLibs {
    const val composeBOM = "2023.08.00"
    const val appcompat = "1.6.1"
    const val clock = "1.1.1"
    const val converter_gson = "2.9.0"
    const val core_splashscreen = "1.0.1"
    const val hilt_android_compiler = "2.44"
    const val hilt_compiler = "1.0.0"
    const val hilt_navigation_compose = "1.1.0-alpha01"
    const val ktx = "1.10.1"
    const val lifecycle_runtime_ktx = "2.6.1"
    const val ok_http = "4.10.0"
    const val lottie_compose = "6.0.0"
    const val material = "1.9.0"
    const val navigation_ui_ktx = "2.7.1"
    const val room_compiler = "2.5.2"
}